// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM graphics stuff for the SDL3 library.
//
//	The DOOM software renderer produces an 8-bit, palettized 320x200
//	framebuffer in screens[0].  SDL3 no longer exposes palettized display
//	surfaces, so each frame we expand that 8-bit buffer through a 32-bit
//	palette into a streaming texture and let the renderer scale it to the
//	window.
//
//-----------------------------------------------------------------------------

static const char
rcsid[] = "$Id: i_x.c,v 1.6 1997/02/03 22:45:10 b1 Exp $";

#include <stdlib.h>

#include <SDL3/SDL.h>

#include "m_swap.h"
#include "doomstat.h"
#include "i_system.h"
#include "v_video.h"
#include "m_argv.h"
#include "d_main.h"

#include "doomdef.h"
#include "c_console.h"	// console state + text-overlay accessors

#include "icon_data.h"	// generated by tools/gen_icon.py (window icon)


static SDL_Window*	window = NULL;
static SDL_Renderer*	renderer = NULL;
static SDL_Texture*	texture = NULL;

// Expanded 32-bit (ARGB8888) palette, rebuilt by I_SetPalette.
static Uint32		palette[256];

// --- Fullcolor (truecolor) mode (Options -> Mod -> Fullcolor) -------------
// The 3D view drawers (r_draw.c) optionally dual-write a parallel truecolor
// framebuffer (screen32) using colormap32 -- a smooth, non-palette-snapped
// version of the 8-bit light colormaps.  I_FinishUpdate then composites the
// truecolor view into the final image wherever 2D (HUD/menu) did not draw
// over it.  See R_RenderPlayerView / I_CaptureTrueColorView.
#define NUMCMAPS	34		// COLORMAP lump = 32 light + invuln + extra
Uint32			colormap32[NUMCMAPS*256];
Uint32*			screen32;	// truecolor 3D-view framebuffer
int			truecolor;	// drawers dual-write while this is set
static byte*		view8snap;	// 8-bit view snapshot (2D-overdraw detect)
static int		view_truecolor;	// a truecolor view was captured this frame
double		fc_lightdim[32];	// per-light-level brightness (exported for HD sprite shading)
static int		cm_dim_ready;
static int		cm_built;	// colormap32 has been built at least once

int			ignore_mouse_time = 0;

extern byte*		colormaps;	// r_data.c (8-bit light tables)
extern int		viewwindowx, viewwindowy, scaledviewwidth, viewheight;

// Rebuild colormap32 from the current (possibly tinted) palette.  Called from
// I_SetPalette so damage/pickup/radsuit palette flashes tint the view too.
static void I_BuildTrueColormaps (void)
{
    int row, i;

    if (!colormaps)
	return;

    // Derive each light level's brightness once, from the 8-bit colormap.
    if (!cm_dim_ready)
    {
	for (row=0 ; row<32 ; row++)
	{
	    double num=0, den=0;
	    for (i=0 ; i<256 ; i++)
	    {
		Uint32 b = palette[i], l = palette[colormaps[row*256+i]];
		den += ((b>>16)&0xff)+((b>>8)&0xff)+(b&0xff);
		num += ((l>>16)&0xff)+((l>>8)&0xff)+(l&0xff);
	    }
	    fc_lightdim[row] = den>0 ? num/den : 1.0;
	}
	cm_dim_ready = 1;
    }

    // Light levels 0..31: smooth-dim the true palette colour (no snapping).
    for (row=0 ; row<32 ; row++)
    {
	double d = fc_lightdim[row];
	for (i=0 ; i<256 ; i++)
	{
	    Uint32 c = palette[i];
	    Uint32 r = (Uint32)(((c>>16)&0xff)*d);
	    Uint32 g = (Uint32)(((c>>8)&0xff)*d);
	    Uint32 b = (Uint32)((c&0xff)*d);
	    colormap32[row*256+i] = 0xff000000u | (r<<16) | (g<<8) | b;
	}
    }
    // Special maps (invuln, extra): keep the stylised 8-bit-mapped colour.
    for (row=32 ; row<NUMCMAPS ; row++)
	for (i=0 ; i<256 ; i++)
	    colormap32[row*256+i] = palette[colormaps[row*256+i]];

    cm_built = 1;
}

// Snapshot the 8-bit view rect right after R_RenderPlayerView, before any HUD
// or menu draws over it, so the composite can tell view pixels from overlays.
void I_CaptureTrueColorView (void)
{
    int y;

    if (!truecolor || !screen32 || !view8snap)
    {
	view_truecolor = 0;
	return;
    }
    // Ensure the truecolor tables exist (colormaps may not have been loaded
    // yet at the first I_SetPalette during startup).
    if (!cm_built)
	I_BuildTrueColormaps();
    for (y=0 ; y<viewheight ; y++)
    {
	int off = (viewwindowy+y)*SCREENWIDTH + viewwindowx;
	memcpy (view8snap+off, screens[0]+off, scaledviewwidth);
    }
    view_truecolor = 1;
}

// Fake mouse handling.
boolean		grabMouse;

extern boolean	consoleactive;		// c_console.h
static int	window_focused = 1;

// Grab (relative-motion) the mouse only while actually playing -- release it
// when the menu or console is up (so the OS cursor is usable) or we lose focus.
static void I_ApplyMouseGrab (void)
{
    static int	applied = -1;
    int		want = grabMouse && window_focused && !menuactive && !consoleactive;

    if (window && want != applied)
    {
	SDL_SetWindowRelativeMouseMode (window, want ? true : false);
	applied = want;
    }
}


//
//  Translates the key
//
int xlatekey(SDL_Keycode sym)
{

    int rc;

    switch(sym)
    {
      case SDLK_LEFT:	rc = KEY_LEFTARROW;	break;
      case SDLK_RIGHT:	rc = KEY_RIGHTARROW;	break;
      case SDLK_DOWN:	rc = KEY_DOWNARROW;	break;
      case SDLK_UP:	rc = KEY_UPARROW;	break;
      case SDLK_ESCAPE:	rc = KEY_ESCAPE;	break;
      case SDLK_RETURN:	rc = KEY_ENTER;		break;
      case SDLK_TAB:	rc = KEY_TAB;		break;
      case SDLK_F1:	rc = KEY_F1;		break;
      case SDLK_F2:	rc = KEY_F2;		break;
      case SDLK_F3:	rc = KEY_F3;		break;
      case SDLK_F4:	rc = KEY_F4;		break;
      case SDLK_F5:	rc = KEY_F5;		break;
      case SDLK_F6:	rc = KEY_F6;		break;
      case SDLK_F7:	rc = KEY_F7;		break;
      case SDLK_F8:	rc = KEY_F8;		break;
      case SDLK_F9:	rc = KEY_F9;		break;
      case SDLK_F10:	rc = KEY_F10;		break;
      case SDLK_F11:	rc = KEY_F11;		break;
      case SDLK_F12:	rc = KEY_F12;		break;

      case SDLK_BACKSPACE:
      case SDLK_DELETE:	rc = KEY_BACKSPACE;	break;

      case SDLK_PAUSE:	rc = KEY_PAUSE;		break;

      case SDLK_EQUALS:	rc = KEY_EQUALS;	break;

      case SDLK_KP_MINUS:
      case SDLK_MINUS:	rc = KEY_MINUS;		break;

      case SDLK_LSHIFT:
      case SDLK_RSHIFT:
	rc = KEY_RSHIFT;
	break;

      case SDLK_LCTRL:
      case SDLK_RCTRL:
	rc = KEY_RCTRL;
	break;

      case SDLK_LALT:
      case SDLK_LGUI:
      case SDLK_RALT:
      case SDLK_RGUI:
	rc = KEY_RALT;
	break;

      default:
        rc = sym;
	break;
    }

    return rc;

}

void I_ShutdownGraphics(void)
{
  if (texture)  { SDL_DestroyTexture(texture);   texture = NULL;  }
  if (renderer) { SDL_DestroyRenderer(renderer); renderer = NULL; }
  if (window)   { SDL_DestroyWindow(window);     window = NULL;   }
  SDL_Quit();
}



//
// I_StartFrame
//
void I_StartFrame (void)
{
    // er?

}

//
// Build a DOOM mouse event from the current SDL mouse button mask.
//
static int I_MouseButtons(SDL_MouseButtonFlags state)
{
    return 0
	| ((state & SDL_BUTTON_MASK(SDL_BUTTON_LEFT))   ? 1 : 0)
	| ((state & SDL_BUTTON_MASK(SDL_BUTTON_MIDDLE)) ? 2 : 0)
	| ((state & SDL_BUTTON_MASK(SDL_BUTTON_RIGHT))  ? 4 : 0);
}

/* This processes SDL events */
void I_GetEvent(SDL_Event *Event)
{
    event_t event;

    switch (Event->type)
    {
      case SDL_EVENT_KEY_DOWN:
	event.type = ev_keydown;
	// MOD: toggle the console on the *physical* grave/tilde key (the key
	// left of 1), regardless of layout -- on a German keyboard that key
	// emits '^'/'°', not '`', so match by scancode and feed the console
	// its expected '`' (CON_TOGGLE).
	event.data1 = (Event->key.scancode == SDL_SCANCODE_GRAVE)
		    ? '`' : xlatekey(Event->key.key);
	D_PostEvent(&event);
        break;

      case SDL_EVENT_KEY_UP:
	event.type = ev_keyup;
	event.data1 = (Event->key.scancode == SDL_SCANCODE_GRAVE)
		    ? '`' : xlatekey(Event->key.key);
	D_PostEvent(&event);
	break;

      case SDL_EVENT_MOUSE_BUTTON_DOWN:
      case SDL_EVENT_MOUSE_BUTTON_UP:
	event.type = ev_mouse;
	event.data1 = I_MouseButtons(SDL_GetMouseState(NULL, NULL));
	event.data2 = event.data3 = 0;
	D_PostEvent(&event);
	break;

      case SDL_EVENT_MOUSE_MOTION:
	event.type = ev_mouse;
	event.data1 = I_MouseButtons(Event->motion.state);
#ifdef _WIN32
	// raw input on Windows reports device coordinates without desktop acceleration,
	// scale it up to feel comfortable compared to Linux
	event.data2 =  ((int)Event->motion.xrel) << 3;
	event.data3 = -((int)Event->motion.yrel) << 3;
#else
	event.data2 =  ((int)Event->motion.xrel) << 2;
	event.data3 = -((int)Event->motion.yrel) << 2;
#endif
	D_PostEvent(&event);
	break;

      case SDL_EVENT_MOUSE_WHEEL:
	// MOD: wheel up/down -> next/prev weapon, as synthetic key presses.
	if (Event->wheel.y != 0)
	{
	    event.type = ev_keydown;
	    event.data1 = (Event->wheel.y > 0) ? KEY_MWHEELUP : KEY_MWHEELDOWN;
	    D_PostEvent(&event);
	}
	break;

      case SDL_EVENT_WINDOW_FOCUS_GAINED:
	window_focused = 1;
	I_ApplyMouseGrab();		// re-grab (e.g. after alt-tab)
	break;

      case SDL_EVENT_WINDOW_FOCUS_LOST:
	window_focused = 0;
	I_ApplyMouseGrab();		// let go so the user can leave the window
	break;

      case SDL_EVENT_QUIT:
	I_Quit();
    }

}

//
// I_StartTic
//
void I_StartTic (void)
{
    SDL_Event Event;

    while ( SDL_PollEvent(&Event) )
	I_GetEvent(&Event);
}


//
// I_UpdateNoBlit
//
void I_UpdateNoBlit (void)
{
    // what is this?
}

//
// I_DrawConsole
// MOD: draw the drop-down console's text with SDL3's built-in font
// (SDL_RenderDebugText, an 8x8 glyph set bundled in SDL3 -- no extra library or
// font file). C_Drawer has already dimmed the backdrop in the 8-bit framebuffer;
// this runs after the game frame is on the renderer and before present.
// Logical presentation is SCREENWIDTH x SCREENHEIGHT, so a render scale of
// `hires` lets us place text in 320x200 (BASE) coordinates and have it scale
// with the resolution, matching the old layout.
//
void I_DrawConsole (void)
{
    int		h, y, i;
    float	s;

    if (renderer == NULL)
	return;
    h = C_BaseHeight ();		// drop height in BASE rows, 0 = closed
    if (h <= 0)
	return;

    s = (float) hires;
    SDL_SetRenderScale (renderer, s, s);
    SDL_SetRenderDrawColor (renderer, 0xd0, 0xd0, 0xd0, 0xff);

    // input line near the bottom of the panel, scrollback rising above it
    y = h - 10;
    SDL_RenderDebugText (renderer, 4, y, C_InputLine ());
    y -= 10;
    for (i = 0; i < C_ScrollCount () && y > -8; i++)
    {
	const char* line = C_ScrollLine (i);
	if (line && line[0])
	    SDL_RenderDebugText (renderer, 4, y, line);
	y -= 8;
    }

    SDL_SetRenderScale (renderer, 1.0f, 1.0f);
}

//
// I_FinishUpdate
//
void I_FinishUpdate (void)
{
    // Track menu/console state: grab while playing, release in the menu.
    I_ApplyMouseGrab();

    static int	lasttic;
    int		tics;
    int		i;
    int		x, y;
    void*	pixels;
    int		pitch;

    // draws little dots on the bottom of the screen
    if (devparm)
    {

	i = I_GetTime();
	tics = i - lasttic;
	lasttic = i;
	if (tics > 20) tics = 20;

	for (i=0 ; i<tics*2 ; i+=2)
	    screens[0][ (SCREENHEIGHT-1)*SCREENWIDTH + i] = 0xff;
	for ( ; i<20*2 ; i+=2)
	    screens[0][ (SCREENHEIGHT-1)*SCREENWIDTH + i] = 0x0;
    }

    // Expand the 8-bit palettized frame into the 32-bit streaming texture.
    if ( !SDL_LockTexture(texture, NULL, &pixels, &pitch) )
	return;

    for (y=0 ; y<SCREENHEIGHT ; y++)
    {
	Uint32*		dst = (Uint32 *)((Uint8 *)pixels + y*pitch);
	unsigned char*	src = screens[0] + y*SCREENWIDTH;

	// Fullcolor: inside the 3D view, use the truecolor framebuffer wherever
	// the 8-bit pixel still matches the pre-HUD snapshot (i.e. no overlay
	// drew there); everywhere else fall back to the palette expansion.
	if (view_truecolor
	    && y >= viewwindowy && y < viewwindowy+viewheight)
	{
	    int		vx0 = viewwindowx;
	    int		vx1 = viewwindowx + scaledviewwidth;
	    Uint32*	s32  = screen32   + y*SCREENWIDTH;
	    byte*	snap = view8snap  + y*SCREENWIDTH;

	    for (x=0 ; x<SCREENWIDTH ; x++)
	    {
		if (x >= vx0 && x < vx1 && src[x] == snap[x])
		    dst[x] = s32[x];
		else
		    dst[x] = palette[src[x]];
	    }
	}
	else
	{
	    for (x=0 ; x<SCREENWIDTH ; x++)
		dst[x] = palette[src[x]];
	}
    }
    view_truecolor = 0;		// consumed; next frame must re-capture

    SDL_UnlockTexture(texture);

    SDL_RenderClear(renderer);
    SDL_RenderTexture(renderer, texture, NULL, NULL);
    I_DrawConsole();			// MOD: console text overlay (SDL3 font)
    SDL_RenderPresent(renderer);
}


//
// I_ReadScreen
//
void I_ReadScreen (byte* scr)
{
    memcpy (scr, screens[0], SCREENWIDTH*SCREENHEIGHT);
}


//
// I_SetPalette
//
void I_SetPalette (byte* pal)
{
    int i;

    for ( i=0; i<256; ++i ) {
	Uint8 r = gammatable[usegamma][*pal++];
	Uint8 g = gammatable[usegamma][*pal++];
	Uint8 b = gammatable[usegamma][*pal++];
	palette[i] = ((Uint32)0xff << 24) | (r << 16) | (g << 8) | b;
    }

    // Keep the truecolor light tables in sync (so palette flashes tint the
    // fullcolor view as well).
    I_BuildTrueColormaps();
}


// Desired display aspect ratio (controls window shape; the frame is stretched
// to fill the window).  0 = 4:3 (classic), 1 = 16:10 (square pixels),
// 2 = 16:9, 3 = stretch/free.
int	screen_aspect = 0;

// MOD: bilinear filtering on the upscale.  This is the closest the 8-bit
// software renderer can get to "antialiasing": it smooths the magnified frame
// (no true MSAA -- there is no geometry/truecolour stage to sample).
int	mod_smooth = 0;

// Non-zero when displaying fullscreen (don't resize the window then).
// Saved/restored via the config file (see m_misc.c defaults).
int	fullscreen_mode = 0;

int I_OutHeight(void)
{
    return (aspect == 0) ? SCREENWIDTH*3/4 : SCREENHEIGHT;
}

//
// (Re)create the streaming texture + logical presentation to match the
// current internal resolution (SCREENWIDTH x SCREENHEIGHT).
//
static void I_CreateTexture(void)
{
    if (texture)
	SDL_DestroyTexture(texture);

    // Render at the internal resolution; SDL scales (aspect-preserving) to the
    // window.  Letterbox keeps the chosen aspect with bars rather than distorting.
    // For 4:3 the logical height is wider-aspect so the 16:10 buffer is shown 4:3.
    SDL_SetRenderLogicalPresentation(renderer, SCREENWIDTH, I_OutHeight(),
				     SDL_LOGICAL_PRESENTATION_LETTERBOX);

    texture = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ARGB8888,
				SDL_TEXTUREACCESS_STREAMING,
				SCREENWIDTH, SCREENHEIGHT);
    if ( texture == NULL )
	I_Error("Could not create texture: %s", SDL_GetError());
    SDL_SetTextureScaleMode(texture,
	mod_smooth ? SDL_SCALEMODE_LINEAR : SDL_SCALEMODE_NEAREST);
}

// MOD: toggle bilinear smoothing at runtime (Options -> Mod).
void I_SetSmoothing(int on)
{
    mod_smooth = on ? 1 : 0;
    if (texture)
	SDL_SetTextureScaleMode(texture,
	    mod_smooth ? SDL_SCALEMODE_LINEAR : SDL_SCALEMODE_NEAREST);
}

//
// Toggle borderless-desktop fullscreen at runtime (from the Video menu).
//
void I_SetFullscreen(int on)
{
    if (!window)
	return;

    fullscreen_mode = on ? 1 : 0;
    SDL_SetWindowFullscreen(window, fullscreen_mode ? true : false);
    SDL_SyncWindow(window);

    if (!fullscreen_mode)
    {
	SDL_SetWindowSize(window, SCREENWIDTH, I_OutHeight());
	SDL_SyncWindow(window);
	SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
    }
    ignore_mouse_time = I_GetTime() + 10;
}

int I_GetFullscreen(void)
{
    return fullscreen_mode;
}

// Cross-module hooks used when changing resolution.
extern int	screenblocks;
extern int	detailLevel;
void		R_SetViewSize (int blocks, int detail);
void		ST_SetRes (void);

//
// V_SetRes
// Change the internal rendering resolution at runtime (scale = 1..7).
// Rebuilds the renderer tables, status bar buffer and SDL texture.
//
void V_SetRes(int scale)
{
    if (scale < 1) scale = 1;
    if (scale > 7) scale = 7;
    if (BASE_WIDTH*scale > MAXWIDTH || BASE_HEIGHT*scale > MAXHEIGHT)
	return;

    widescreen   = (aspect == 1);		// only 16:9 widens the buffer (Hor+)
    hires        = scale;
    SCREENHEIGHT = BASE_HEIGHT * scale;
    NONWIDEWIDTH = BASE_WIDTH  * scale;		// the 16:10 reference width

    if (widescreen)
    {
	SCREENWIDTH = SCREENHEIGHT * 16 / 9;	// Hor+ 16:9 buffer
	if (SCREENWIDTH > MAXWIDTH) SCREENWIDTH = MAXWIDTH;
	SCREENWIDTH &= ~3;			// keep a multiple of 4
    }
    else
	SCREENWIDTH = NONWIDEWIDTH;		// 4:3 and 16:10 share the 320*hires buffer
						// (4:3 is the same buffer shown stretched)

    // half the extra width, in BASE (320) coords -- HUD edges shift by this
    WIDESCREENDELTA = ((SCREENWIDTH - NONWIDEWIDTH) / scale) / 2;

    if (renderer)
	I_CreateTexture();

    // Rebuild resolution-dependent state.  R_SetViewSize sets setsizeneeded,
    // so the next D_Display rebuilds the view tables and repaints the border
    // background at the new resolution.
    ST_SetRes();				// status bar background buffer + refresh
    R_SetViewSize (screenblocks, detailLevel);

    // Grow/shrink the window to match the new resolution + output aspect (windowed).
    if (window && !fullscreen_mode)
    {
	SDL_SetWindowSize(window, SCREENWIDTH, I_OutHeight());
	SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
    }
    ignore_mouse_time = I_GetTime() + 10;
}


void I_InitGraphics(void)
{

    static int	firsttime=1;
    Uint32	window_flags = 0;
    int		w, h, startscale;

    if (!firsttime)
	return;
    firsttime = 0;

    // Fullcolor framebuffers, sized for the maximum internal resolution so
    // they never need reallocating on a resolution change.
    screen32  = malloc (MAXWIDTH*MAXHEIGHT*sizeof(Uint32));
    view8snap = malloc (MAXWIDTH*MAXHEIGHT);

    // Grab the mouse by default: relative-motion mode drives turning and keeps
    // the cursor confined to the window (essential in windowed mode).  Focus
    // changes release/re-grab it (see I_GetEvent) so alt-tab still works.
    // -nograbmouse opts out.
    grabMouse = !M_CheckParm("-nograbmouse");

    // aspect / hires / fullscreen_mode come from the config file
    // (loaded by M_LoadDefaults before this runs).  Optional -aspect overrides.
    aspect &= 3;
    {
	int p = M_CheckParm("-aspect");
	if (p && p < myargc-1)
	    aspect = atoi(myargv[p+1]) & 3;
    }

    // Initial resolution scale (also drives the window size).  Defaults to the
    // saved value; -1..-4 / -render N override.  Changeable later in the menu.
    startscale = hires;
    if (M_CheckParm("-1")) startscale = 1;
    if (M_CheckParm("-2")) startscale = 2;
    if (M_CheckParm("-3")) startscale = 3;
    if (M_CheckParm("-4")) startscale = 4;
    {
	int p = M_CheckParm("-render");
	if (p && p < myargc-1)
	    startscale = atoi(myargv[p+1]);
    }
    if (startscale < 1) startscale = 1;
    if (startscale > 7) startscale = 7;

    // Initial window size = 16:10 reference size for the startscale.
    // It will be resized to correct widescreen size in V_SetRes.
    w = BASE_WIDTH * startscale;
    h = BASE_HEIGHT * startscale;

    window_flags |= SDL_WINDOW_RESIZABLE;
    if (fullscreen_mode || M_CheckParm("-fullscreen"))
    {
        window_flags |= SDL_WINDOW_FULLSCREEN;
	fullscreen_mode = 1;
    }

    window = SDL_CreateWindow("SDLDoom-SDL3", w, h, window_flags);
    if ( window == NULL )
	I_Error("Could not create %dx%d window: %s", w, h, SDL_GetError());

    // Window icon (matches the exe icon; data embedded via icon_data.h).
    {
	SDL_Surface* icon = SDL_CreateSurfaceFrom(
	    ICON_W, ICON_H, SDL_PIXELFORMAT_RGBA32,
	    (void *)icon_rgba, ICON_W * 4);
	if (icon)
	{
	    SDL_SetWindowIcon(window, icon);
	    SDL_DestroySurface(icon);
	}
    }

    renderer = SDL_CreateRenderer(window, NULL);
    if ( renderer == NULL )
	I_Error("Could not create renderer: %s", SDL_GetError());

    I_CreateTexture();

    SDL_HideCursor();
    I_ApplyMouseGrab();		// grab now (menu not up yet)

    // screens[0..3] are allocated by V_Init at the maximum resolution; the
    // 3D view, HUD etc. render into screens[0] at the current SCREENWIDTH.
    // V_SetRes also sizes the window to match (via I_ApplyAspect).
    V_SetRes(startscale);
}
