#!/bin/sh
# Regenerate ../../gpu_shaders.h from the GLSL blit shaders.
# Requires: glslang-tools (glslangValidator).  See i_video.c (SDL_GPU backend).
set -e
cd "$(dirname "$0")"
glslangValidator -V blit.vert -o blit.vert.spv
glslangValidator -V blit.frag -o blit.frag.spv
emit() {
  python3 - "$1" "$2" <<'PY'
import sys
name, path = sys.argv[1], sys.argv[2]
data = open(path,'rb').read()
print(f"static const unsigned char {name}[] = {{")
for i in range(0,len(data),12):
    print("    " + "".join(f"0x{b:02x}," for b in data[i:i+12]))
print("};")
print(f"static const unsigned int {name}_len = {len(data)};\n")
PY
}
{
echo "// gpu_shaders.h -- GENERATED by tools/gpu/gen_gpu_shaders.sh, do not edit."
echo "// Fullscreen-blit shaders for the SDL_GPU presentation backend (i_video.c)."
echo "#ifndef GPU_SHADERS_H"
echo "#define GPU_SHADERS_H"
echo
emit gpu_blit_vert_spv blit.vert.spv
emit gpu_blit_frag_spv blit.frag.spv
echo "#endif"
} > ../../gpu_shaders.h
rm -f blit.vert.spv blit.frag.spv
echo "wrote gpu_shaders.h"
