#!/usr/bin/env python3
"""Generate the SDLDoom application icon.

Outputs two artifacts consumed by the build:
  * sdldoom.ico  - multi-resolution Windows icon, linked into the exe via
                   sdldoom.rc / windres.
  * icon_data.h  - 64x64 RGBA pixel array, embedded for SDL_SetWindowIcon so
                   the running window shows the same icon (no SDL_image dep).

Run from the repo root:  python tools/gen_icon.py
Requires Pillow (PIL).
"""

import os
import math
from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- colours (DOOM-ish: gunmetal background, hot red/orange emblem) ----------
BG_TOP    = (40, 40, 46)
BG_BOTTOM = (12, 10, 10)
BORDER    = (120, 24, 16)
GLOW      = (255, 70, 24)
LETTER    = (240, 60, 30)
LETTER_HI = (255, 150, 80)

SS = 1024  # supersample master size; downscaled to each target


def load_font(size):
    """Best-effort heavy display font for the emblem letter."""
    for name in ("impact.ttf", "ariblk.ttf", "arialbd.ttf", "arial.ttf"):
        path = os.path.join(os.environ.get("WINDIR", r"C:\Windows"),
                            "Fonts", name)
        if os.path.exists(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def rounded_mask(size, radius):
    m = Image.new("L", (size, size), 0)
    d = ImageDraw.Draw(m)
    d.rounded_rectangle([0, 0, size - 1, size - 1], radius=radius, fill=255)
    return m


def vgradient(size, top, bottom):
    grad = Image.new("RGB", (1, size))
    for y in range(size):
        t = y / (size - 1)
        grad.putpixel((0, y), tuple(
            int(top[c] + (bottom[c] - top[c]) * t) for c in range(3)))
    return grad.resize((size, size))


def render_master():
    size = SS
    radius = int(size * 0.18)

    # gradient background clipped to a rounded square
    base = vgradient(size, BG_TOP, BG_BOTTOM).convert("RGBA")
    mask = rounded_mask(size, radius)
    base.putalpha(mask)

    draw = ImageDraw.Draw(base)

    # bevelled red border
    bw = int(size * 0.045)
    draw.rounded_rectangle([bw // 2, bw // 2, size - 1 - bw // 2,
                            size - 1 - bw // 2],
                           radius=radius, outline=BORDER, width=bw)

    # emblem letter, with an outer glow on its own layer
    font = load_font(int(size * 0.74))
    text = "D"
    glow = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    bbox = gd.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    tx = (size - tw) // 2 - bbox[0]
    ty = (size - th) // 2 - bbox[1] - int(size * 0.02)
    gd.text((tx, ty), text, font=font, fill=GLOW)
    glow = glow.filter(ImageFilter.GaussianBlur(int(size * 0.03)))
    base = Image.alpha_composite(base, glow)
    base = Image.alpha_composite(base, glow)  # intensify

    # the solid letter, with a lighter top highlight
    letter = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ld = ImageDraw.Draw(letter)
    ld.text((tx, ty), text, font=font, fill=LETTER)
    ld.text((tx, ty - int(size * 0.012)), text, font=font, fill=LETTER_HI)
    ld.text((tx, ty), text, font=font, fill=LETTER)
    base = Image.alpha_composite(base, letter)

    # re-clip to the rounded square so glow doesn't bleed past the corners
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    out.paste(base, (0, 0), mask)
    return out


def main():
    master = render_master()

    sizes = [256, 128, 64, 48, 32, 16]
    imgs = [master.resize((s, s), Image.LANCZOS) for s in sizes]

    ico_path = os.path.join(ROOT, "sdldoom.ico")
    imgs[0].save(ico_path, format="ICO",
                 sizes=[(s, s) for s in sizes])
    print("wrote", ico_path)

    # 64x64 RGBA for the SDL window icon
    win = master.resize((64, 64), Image.LANCZOS)
    px = win.tobytes()  # RGBA, row-major top-to-bottom
    h_path = os.path.join(ROOT, "icon_data.h")
    with open(h_path, "w") as f:
        f.write("// Generated by tools/gen_icon.py - do not edit.\n")
        f.write("// 64x64 RGBA8888 (top-to-bottom) for SDL_SetWindowIcon.\n")
        f.write("#ifndef ICON_DATA_H\n#define ICON_DATA_H\n\n")
        f.write("#define ICON_W 64\n#define ICON_H 64\n\n")
        f.write("static const unsigned char icon_rgba[64*64*4] = {\n")
        for i in range(0, len(px), 16):
            row = ",".join(str(b) for b in px[i:i + 16])
            f.write("    " + row + ",\n")
        f.write("};\n\n#endif\n")
    print("wrote", h_path)


if __name__ == "__main__":
    main()
