#!/usr/bin/env python3
# Generate footsteps.wad (DMX sounds) + C tables from the zk-resources footsteps.pk3.
import os, re, sys, zipfile, subprocess, struct, tempfile, shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
PK3  = os.path.join(ROOT, "..", "run", "footsteps.pk3")
OUT_WAD = os.path.join(ROOT, "..", "run", "footsteps.wad")
GEN = os.path.join(ROOT, "gen")
os.makedirs(GEN, exist_ok=True)

tmp = tempfile.mkdtemp()
with zipfile.ZipFile(PK3) as z:
    z.extractall(tmp)

# --- read text defs ---
def rd(name):
    with open(os.path.join(tmp, name), "r", errors="replace") as f:
        return f.read()

sndinfo = rd("sndinfo.txt")
language = rd("language.txt")

# logical sound name -> lump name (e.g. step/dirt1 -> DSDIRT1)
logical2lump = {}
for m in re.finditer(r'^\s*(step/\S+)\s+(\S+)\s*$', sndinfo, re.M):
    logical2lump[m.group(1)] = m.group(2)

# $random group -> [logical names]   (e.g. step/dirt -> step/dirt1..6)
group2logicals = {}
for m in re.finditer(r'\$random\s+(step/\S+)\s*\{([^}]*)\}', sndinfo):
    group2logicals[m.group(1)] = m.group(2).split()

# --- collect file inventory: BASENAME(upper,no ext) -> path ---
base2path = {}
for dp, dn, fn in os.walk(os.path.join(tmp, "sounds")):
    for f in fn:
        b = os.path.splitext(f)[0].upper()
        base2path[b] = os.path.join(dp, f)

# lump -> sfx name used by the engine (engine looks up "ds"+name)
def sfxname(lump):
    return lump[2:].lower() if lump.upper().startswith("DS") else lump.lower()

# --- terrain groups: C enum id from group string ---
def ter_id(group):           # step/metal/a -> TER_METAL_A
    return "TER_" + group[len("step/"):].upper().replace("/", "_")

# distinct groups referenced (default + per-flat), preserve a stable order
order = ["step/default","step/water","step/carpet","step/dirt","step/gravel",
         "step/hard","step/metal/a","step/metal/b","step/rock","step/snow",
         "step/tile/a","step/tile/b","step/wood","step/slime","step/slimy","step/lava"]

# --- flat -> group from language.txt ---
flat2group = {}
default_group = "step/default"
for m in re.finditer(r'^\s*STEP_([A-Z0-9_]+)\s*=\s*"([^"]*)"\s*;', language, re.M):
    flat, grp = m.group(1), m.group(2)
    if flat == "FLATS":
        continue
    if flat == "DEFAULT":
        default_group = grp or "step/default"
        continue
    flat2group[flat] = grp        # grp may be "" (silent, e.g. F_SKY1)

# --- build the set of lumps we actually need, convert to DMX, write WAD ---
def to_dmx(path):
    raw = subprocess.run(
        ["ffmpeg","-v","error","-y","-i",path,"-ac","1","-ar","11025","-f","u8","-"],
        stdout=subprocess.PIPE, check=True).stdout
    hdr = struct.pack("<HHI", 3, 11025, len(raw))
    return hdr + raw

lumps = []   # (NAME, bytes)
needed = []
for g in order:
    for logical in group2logicals.get(g, []):
        lump = logical2lump[logical]
        if lump not in [n for n,_ in lumps]:
            path = base2path.get(lump.upper())
            if not path:
                print("MISSING FILE for lump", lump, file=sys.stderr); sys.exit(1)
            lumps.append((lump.upper(), to_dmx(path)))

# write PWAD
with open(OUT_WAD, "wb") as w:
    w.write(b"PWAD")
    w.write(struct.pack("<i", len(lumps)))
    w.write(struct.pack("<i", 0))      # patch infotableofs later
    dirents = []
    pos = 12
    for name, data in lumps:
        dirents.append((pos, len(data), name))
        w.write(data); pos += len(data)
    infotableofs = pos
    for filepos, size, name in dirents:
        w.write(struct.pack("<ii", filepos, size))
        w.write(name.encode("ascii")[:8].ljust(8, b"\0"))
    w.seek(8); w.write(struct.pack("<i", infotableofs))
print("Wrote", OUT_WAD, "with", len(lumps), "lumps")

# --- emit C: sfx enum + S_sfx rows ---
sfxnames = [sfxname(n) for n,_ in lumps]
with open(os.path.join(GEN,"sfx_enum.txt"),"w") as f:
    f.write("    // --- footstep sounds (footsteps.wad) ---\n")
    for s in sfxnames:
        f.write("    sfx_%s,\n" % s)
with open(os.path.join(GEN,"sfx_rows.txt"),"w") as f:
    f.write("  // --- footstep sounds (footsteps.wad) ---\n")
    for s in sfxnames:
        f.write('  { "%s", false, 32, 0, -1, -1, 0 },\n' % s)

# --- emit C: terrain variant arrays + enum + flat table (body for p_footstep.c) ---
def variants(group):
    return [sfxname(logical2lump[l]) for l in group2logicals.get(group, [])]

with open(os.path.join(ROOT,"..","footstep_tables.h"),"w") as f:
    f.write("// AUTO-GENERATED by tools/gen_footsteps.py - do not edit by hand.\n")
    f.write("// Regenerate with: python tools/gen_footsteps.py\n\n")
    f.write("typedef enum {\n")
    for g in order:
        f.write("    %s,\n" % ter_id(g))
    f.write("    TER_SILENT,\n    NUMTERRAIN\n} terrain_t;\n\n")
    # variant arrays
    for g in order:
        vs = variants(g)
        f.write("static const int ter_%s[] = { %s };\n" %
                (ter_id(g)[4:].lower(), ", ".join("sfx_"+v for v in vs)))
    f.write("\nstatic const struct { const int* sfx; int count; } terrain_sounds[NUMTERRAIN] = {\n")
    for g in order:
        nm = ter_id(g)[4:].lower()
        f.write("    { ter_%s, %d },\n" % (nm, len(variants(g))))
    f.write("    { 0, 0 },   // TER_SILENT\n};\n\n")
    # flat -> terrain table
    f.write("static const struct { const char name[9]; terrain_t terrain; } flat_terrain[] = {\n")
    for flat, grp in sorted(flat2group.items()):
        t = "TER_SILENT" if grp == "" else ter_id(grp)
        f.write('    { "%s", %s },\n' % (flat, t))
    f.write("};\n")
    f.write("#define NUM_FLAT_TERRAIN (sizeof(flat_terrain)/sizeof(flat_terrain[0]))\n")
    f.write("#define TER_DEFAULT_GROUP %s\n" % ter_id(default_group))

print("Wrote C fragments to", GEN)
print("terrains:", len(order), " sounds:", len(lumps), " flats:", len(flat2group))
shutil.rmtree(tmp, ignore_errors=True)
